### ISSUE TITLE
WP 5.7: wp_localize_script requires array

### ISSUE THREAD

**Issue by BrianHenryIE** [jamiebergen/plugin-notes-plus#16]
Looks like a deprecation with the latest WordPress.

Affecting: https://github.com/jamiebergen/plugin-notes-plus/blob/390b7bdc60293277180c8f0011da4eb5541a2062/admin/class-plugin-notes-plus-admin.php#L118

```
{
  "function": "WP_Scripts::localize",
  "message": "The <code>$l10n</code> parameter must be an array. To pass arbitrary data to scripts, use the <code>wp_add_inline_script()</code> function instead.",
  "version": "5.7.0",
  "exception": "
    #0 /path/to/wp-includes/class.wp-scripts.php(496): _doing_it_wrong('WP_Scripts::loc...', 'The <code>$l10n...', '5.7.0')
    #1 /path/to/wp-includes/functions.wp-scripts.php(221): WP_Scripts->localize('pnp_updates_scr...', 'updates', '[[],{\"62\":{\"not...')
    #2 /path/to/wp-content/plugins/plugin-notes-plus/admin/class-plugin-notes-plus-admin.php(118): wp_localize_script('pnp_updates_scr...', 'updates', '[[],{\"62\":{\"not...')
    #3 /path/to/wp-includes/class-wp-hook.php(292): Plugin_Notes_Plus_Admin->enqueue_scripts('update-core.php')
    #4 /path/to/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
    #5 /path/to/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
    #6 /path/to/wp-admin/admin-header.php(102): do_action('admin_enqueue_s...', 'update-core.php')
    #7 /path/to/wp-admin/update-core.php(980): require_once('/home/customer/...')
    #8 {main}
  "
}
```

I only noticed this in the logs. The notes are appearing fine on the updates screen!

**Comment by jamiebergen** [comment]
Thank you very much for catching this! I'll fix this and push out an update when I get a chance.

**Comment by jamiebergen** [comment]
### To reproduce:

1. Set: `define( 'WP_DEBUG', true );`
2. Go to /wp-admin/update-core.php
3. See the PHP error: `Notice: WP_Scripts::localize was called <strong>incorrectly</strong>. The <code>$l10n</code> parameter must be an array. To pass arbitrary data to scripts, use the <code>wp_add_inline_script()</code> function instead.`

### To fix:

On line 118 of `wp-content/plugins/plugin-notes-plus/admin/class-plugin-notes-plus-admin.php`, `$updates_json_str` needs to be an array instead of a string.

See documentation for `wp_localize_script` here: https://developer.wordpress.org/reference/functions/wp_localize_script/

I'll finalize this fix and push out an update in the next few days.
